.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 11/17/13
.Dt monster 1
.Os Darwin
.Sh NAME
.Nm monster
.Nd a command-line cookie editor for OS X
.Sh SYNOPSIS
.Nm monster
get
.Ar url
.Op Ar key
.Nm monster
set
.Ar url
.Ar key
.Ar value
.Op Ar expiry
.Nm monster
eat
.Ar url
.Ar key
.Sh DESCRIPTION
The
.Nm
utility lists and/or modifies the current user's cookie jar. This can be
useful, for example, during local web services development, or for automated
management of externally delivered cookies.
.Pp
.Nm
supports three modes of operation, as follows:
.Bl -tag -width -indent
.It get
Get the value of the cookie(s) for url
.Ar url
with key
.Ar key .
If
.Ar key
is not provided, all cookies set for
.Ar url
will be listed.
.It set
Set a cookie for url
.Ar url
with key
.Ar key
and value
.Ar value .
Both
.Ar key
and
.Ar value
are required.
.Ar expiry
is an optional expiration date for the set cookie, in the form <N>
.Ar units
notation;
.Ar units
may be one of:
.Bl -tag -width -indent
.It s
seconds
.It m
minutes
.It h
hours
.It d
days
.It y
years
.El
.It eat
Remove the the cookie for url
.Ar url
with key
.Ar key .
.El
.Pp
Both set and eat forms require that the user's cookie jar be writeable. Specifically,
the write policy on the cookie jar must be
.Ar NSHTTPCookieAcceptPolicyAlways .
.Nm
will attempt to set the policy on the cookie jar if required, but depending on the
user's browser security settings, this may fail.
.Pp
.Sh SEE ALSO
.Xr curl 1